import Foundation

/// Bundles (curated "recipes") — a named set of Homebrew packages plus the
/// capability requirements and post-install setup guidance the UI renders. The
/// data contract mirrors the Tauri side (`Bundle`/`BundlePackage`/`SetupStep`
/// in src-tauri/src/types.rs + src/lib/types.ts) and the JSON Schema at
/// recipes/recipe.schema.json. Parsed from the bundled `bundles.json`
/// (generated by scripts/validate-recipes.mjs) at launch by `BundleCatalog`.
///
/// Tolerant by design: every field beyond the required core is optional (missing
/// → nil), unknown JSON keys are ignored by Codable, and a single malformed
/// recipe is skipped rather than failing the whole catalog (see `BundleCatalog`).
///
/// NOTE: named `BrewBundle`, not `Bundle`. A module-level type named `Bundle`
/// would shadow `Foundation.Bundle` — including inside SwiftPM's generated
/// `resource_bundle_accessor.swift`, which references `Bundle.module` unqualified
/// and can't be edited — breaking every bundled-resource lookup in this target.
/// The `Brew*` prefix also matches `BrewService`/`BrewOutputParsing`.
public struct BrewBundle: Sendable, Codable, Identifiable, Hashable {
    /// kebab-case identifier, unique across the catalog (e.g. "local-llm").
    public let id: String
    /// Display name (≤40 chars per the schema).
    public let name: String
    /// One-line pitch (≤90 chars).
    public let tagline: String
    /// One of AI / Graphics / Media / Development / Data / Productivity.
    public let category: String
    /// Optional icon token (SF Symbol-ish name the UI maps to a glyph).
    public let icon: String?
    /// The packages this bundle installs (≥1). Formula or cask.
    public let packages: [BundlePackage]
    /// Third-party tap that must be trusted before install, if any.
    public let tap: String?
    /// Host requirements gate (RAM / disk / arch / gpu). Reused M1 type.
    public let requires: BundleRequires?
    /// RAM-tier → capability note, keyed by integer-string GB (e.g. "16").
    public let capabilityNotes: [String: String]?
    /// Ordered post-install steps (start a service, open a URL, run a command…).
    public let setup: [SetupStep]?
    /// Free-text caveats shown before/after install (≤240 chars).
    public let caveats: String?
    /// "Further reading" links (label + https url).
    public let links: [BundleLink]?
    /// Who curates this recipe (e.g. "brew-browser").
    public let maintainer: String?
    /// First app version the recipe shipped in (e.g. "0.7.0").
    public let addedIn: String?

    public init(id: String, name: String, tagline: String, category: String,
                icon: String? = nil, packages: [BundlePackage], tap: String? = nil,
                requires: BundleRequires? = nil, capabilityNotes: [String: String]? = nil,
                setup: [SetupStep]? = nil, caveats: String? = nil,
                links: [BundleLink]? = nil, maintainer: String? = nil, addedIn: String? = nil) {
        self.id = id
        self.name = name
        self.tagline = tagline
        self.category = category
        self.icon = icon
        self.packages = packages
        self.tap = tap
        self.requires = requires
        self.capabilityNotes = capabilityNotes
        self.setup = setup
        self.caveats = caveats
        self.links = links
        self.maintainer = maintainer
        self.addedIn = addedIn
    }
}

/// One package inside a bundle. `kind` is "formula" or "cask" (kept as a plain
/// String for tolerant parsing — an unknown kind survives rather than dropping
/// the whole recipe).
public struct BundlePackage: Sendable, Codable, Hashable {
    public let name: String
    public let kind: String

    public init(name: String, kind: String) {
        self.name = name
        self.kind = kind
    }
}

/// One post-install setup step. `kind` selects which of the optional fields are
/// meaningful: service→`service`, open→`url`, reveal→`path`, command→`run`
/// (always `external:true` per the contract — the app never auto-runs shell),
/// note→`text`. All non-`kind` fields are optional so any step shape parses.
public struct SetupStep: Sendable, Codable, Hashable {
    public let kind: String
    public let service: String?
    public let label: String?
    public let url: String?
    public let path: String?
    public let run: String?
    public let external: Bool?
    public let text: String?

    public init(kind: String, service: String? = nil, label: String? = nil,
                url: String? = nil, path: String? = nil, run: String? = nil,
                external: Bool? = nil, text: String? = nil) {
        self.kind = kind
        self.service = service
        self.label = label
        self.url = url
        self.path = path
        self.run = run
        self.external = external
        self.text = text
    }
}

/// A "further reading" link on a bundle.
public struct BundleLink: Sendable, Codable, Hashable {
    public let label: String
    public let url: String

    public init(label: String, url: String) {
        self.label = label
        self.url = url
    }
}

// MARK: - Lossy decoding

/// Decodes `T` but captures any decode error instead of throwing, so it can be
/// used inside `[Throwable<T>]` to decode an array element-by-element where bad
/// elements are dropped rather than failing the whole array. (A directly-thrown
/// element decode does not advance `JSONDecoder`'s unkeyed container, so the
/// error must be caught at the element boundary — this wrapper does exactly that.)
struct Throwable<T: Decodable>: Decodable {
    let result: Result<T, Error>
    init(from decoder: Decoder) throws {
        result = Result(catching: { try T(from: decoder) })
    }
}

/// On-disk `bundles.json` shape: `{ schemaVersion, generatedAt?, bundles: [...] }`.
/// `schemaVersion`/`generatedAt` are optional (the generator omits the timestamp
/// for deterministic diffs); each bundle is wrapped in `Throwable` so a single
/// malformed recipe is skipped, not fatal.
private struct BundleFile: Decodable {
    let schemaVersion: Int?
    let bundles: [Throwable<BrewBundle>]
}

// MARK: - Loader

/// Parses the bundled `bundles.json` into `[Bundle]`, tolerantly. A Sendable
/// value type (mirrors the `CategoryCatalog`/`EnrichmentCatalog` bundled-data
/// loaders); call `load()` off the main thread from `AppModel.loadBundledData()`.
public struct BundleCatalog: Sendable {
    public init() {}

    /// Decode the bundled catalog. Returns `[]` if the resource is missing or
    /// the top-level JSON is malformed; individual malformed recipes are simply
    /// dropped so the remaining valid bundles still load. Preserves file order.
    public func load() -> [BrewBundle] {
        guard let url = Bundle.module.url(forResource: "bundles", withExtension: "json"),
              let data = try? Data(contentsOf: url) else {
            return []
        }
        return Self.parse(data)
    }

    /// Decode bundles from raw JSON bytes (the testable core of `load()`).
    /// Skips recipes that fail to decode; returns `[]` on a malformed top level.
    static func parse(_ data: Data) -> [BrewBundle] {
        guard let file = try? JSONDecoder().decode(BundleFile.self, from: data) else {
            return []
        }
        return file.bundles.compactMap { try? $0.result.get() }
    }
}
